version: '3.0'

services:
  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - 8081:8080
    networks:
      - backend

  mysql:
    image: mysql
    volumes:
      - ./Data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rsail
    restart: always
    networks:
      - backend

  webapp:
    build: .
    image: rsailapp:latest
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - backend

networks:
  frontend:
    external:
      name: proxy_proxy
  backend:
      